# 开发环境配置文件
# 1.只需要对外暴露服务
#server:
#  port: 8080
# 2.spring相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql-connector-java  6.0以上要使用这个，并且指定时区，UTC比中国早8个小时可以改成Asia/Shanghai
    url: jdbc:mysql://127.0.0.1:3306/onlinehospital?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid: # Druid数据源的配置
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        # login-username: root
        # login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true # 启用数据源监控
# Mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印完整带参数SQL语句
  mapper-locations: classpath:mapper/*Mapper.xml # 扫描mapper对象 Mapper.xml统一放在resource目录下
  global-config:
    db-config:
      id-type: auto # id自动生成
# dubbo配置
dubbo:
  config-center:
    timeout: 20000
  application:
    name: hospital-erp-service # 该项目部署在Zookeeper上的服务名称
  registry:
    address: zookeeper://192.168.125.20:2181?timeout=20000
  consumer:
    check: false # 是否检查消费者
  protocol:
    name: dubbo # name 指定的是传输协议的名称：dubbo rmi hessian webservice
    port: 20882

