# 开发环境配置文件
# 1.设置项目启动端口
server:
  port: 8080
# 2.spring相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql-connector-java  6.0以上要使用这个，并且指定时区，UTC比中国早8个小时可以改成Asia/Shanghai
    url: jdbc:mysql://127.0.0.1:3306/onlinehospital?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid: # Druid数据源的配置
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        # login-username: root
        # login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true # 启用数据源监控
  # Redis配置
  redis:
    port: 6390
    host: 192.168.125.20
    password: root
  mvc: # 前端接收的日期转成这种形式
    date-format: yyyy-MM-dd HH:mm:ss
  jackson: # 后端数据库获取数据转换格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 # 时区
# shiro配置
shiro:
  anon-urls: # 配置放行，不需要验证token
    - /login/doLogin* # 登录
    - /login/captcha* # 获取验证码
    - /login/logout* # 退出
    - /druid/**
  authc-urls: # 其他路径都需要拦截
    - /**
# Mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印完整带参数SQL语句
  mapper-locations: classpath:mapper/*Mapper.xml # 扫描mapper对象 Mapper.xml统一放在resource目录下
  global-config:
    db-config:
      id-type: auto # id自动生成

# fastdfs配置
fdfs:
  so-timeout: 2500 # 读取时间
  connect-timeout: 600 # 连接超时时间
  thumb-image: # 缩略图信息
    width: 100
    height: 100
  tracker-list:
    - 192.168.125.20:22122
upload:
  base-url: http://192.168.125.20:8888
  allow-types: # 运行上传的类型
    - image/jpeg
    - image/png
    - image/bmp
# dubbo配置
dubbo:
  config-center:
    timeout: 10000
  application:
    name: hospital-system-web-service # 该项目部署在Zookeeper上的服务名称
  registry:
    address: zookeeper://192.168.125.20:2181?timeout=10000
  consumer:
    check: false # 是否检查消费者
